### ISSUE TITLE
[ERROR] SortService returned a non-zero exit status

### ISSUE THREAD

**Issue by piatekmj** [PacificBiosciences/pbalign#57]
I'm following [pbalign tutorial on large datasets](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign). I split my original fofn into subsets containing only three bax.h5 files, there is 14 of them.

I run pbalign as following:
`pbalign file_1 reference.fasta out_file_1.cmp.h5 --forQuiver`

For every single subset of original fofn I get error message:
`[ERROR] SortService returned a non-zero exit status.`
Unfortunately there is no more informative messages.

Additionally for one subfile I get different message instead:
`[ERROR] FilterService returned a non-zero exit status. Error parsing alignment line 103. Missing or error in field PNEXT`

The original movies are about ~1GB in size.

I'm using pbalign as part of smrtanalysis_v2.3 so not sure if the solution from issue #22 would help.

Any advice would be appreciated.

**Comment by ylipacbio** [comment]
Would you please try the following command for quick diagnostics

```
pbalign -vv whatever-movie.1.bax.h5 reference.fasta out_file_1.cmp.h5 --forQuiver --algorithmOptions=' -holeNumbers 1-5000 ' --keepTmpFiles
```

**Comment by piatekmj** [comment]
It finished with the same result. Excerpt from the log:
`[INFO] pbalign version: 0.2.0.138342`
...
`[INFO] ForQuiverService: Sort.`
`[INFO] SortService: Sort a cmp.h5 file using cmph5tools.py.`
`[DEBUG] SortService: Call "cmph5tools.py -vv  sort --deep --inPlace out_file_1.cmp.h5 "`
`[ERROR] SortService returned a non-zero exit status. `

No other messages returned.
sam file gets created. Seems to be formatted the right way.

Would you like me to report on other tmp files?

**Comment by piatekmj** [comment]
Just to add to the thread.

The tutorial has now moved from the[ original link](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign) I provided to a [new location](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-RSII-dataset-using-pbalign-and-blasr-in-SMRTAnalysis-2.3-(and-previous-version)), hence the update.

**Comment by ylipacbio** [comment]
Please call ```cmph5tools.py -vv sort --deep --inPlace out.cmp.h5``` from command line to check if you need to reinstall pbh5tools. 

If this does not solve this issue, then the problem might be with pbalign and blasr versions.

The latest pbalign and blasr in github (which are compatible with SMRTAnalysis 3.0+) are not backward compatible with legacy pbalign and blasr in SMRTAnalysis 2.3 and can not take bax.h5 files as input and produce cmp.h5. In order to align reads in bax.h5 files, you may either 
* install legacy pbalign and blasr compatible with SMRTAnalysis 2.3 and call ```pbalign fofn_of_bax_h5_files ref.fasta out.cmp.h5 --forQuiver```
* install latest pbalign and blasr compatible with SMRTAnalysis 3.0 and first convert bax.h5 files to bam files and then call ``` pbalign bam_or_dataset ref.fasta out.bam```. 

Regarding pbalign and blasr versions:
https://github.com/PacificBiosciences/pbalign/wiki#attention-pbalign-and-blasr-has-been-significantly-changed-in-smrtanalysis-v30-and-blasr-and-pbalign-in-smrtanalysis-v30-and-later-version-are-not-backward-compatible-with-legacy-blasr-and-pbalign-in-smrtanalysis-v23-and-previous-version

A tutorial for processsing bax.h5 files: 
https://github.com/PacificBiosciences/pbalign/wiki/Mapping-RS-II-reads-(in-movie.bax.h5)-and-calling-consensus-using-pbalign-BLASR-while--sam-option-is-deprecated

A tutorial for installing pbalign and blasr of the version that  you need: 
https://github.com/PacificBiosciences/pbalign/wiki/Install-pbalign-and-blasr-using-pitchfork
