### ISSUE TITLE
[Question] Running time

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/pbalign#69]
Hi everyone !

I've launched 3 days ago pbalign using my data (containing 147 SMRT cells, total amount of 658 Giga of data), but I start to having doubt on my strategy as blasr is still running, and as my RAM and swap start to be fully used (I have 128 Giga of RAM, almost the same for swap).

According to the amount of input data, do you have an idea of how long this analysis will last ? Or at least if it will end one day ? Should I have taken less data ?

Thanks for your advices,

Cheers,

Roxane

**Comment by armintoepfer** [comment]
Why are you aligning all cells at one time instead of doing it cell by cell? If they are all from the same organism, aligning one cell will give you a rough estimate for the remaining cells. No one can tell you how long it will take, as it depends on your CPU core count, CPU speed, reference length and complexity, cell yield, library size...

**Comment by RxLoutre** [comment]
Okay, thanks a lot for your answer.

My run failed 2 days ago because I had no enough memory, so I guess I'm going to try with just one or two cells to test.
